INHERIT: ./_base.yml

site_url: https://mmesh.local/docs/
use_directory_urls: true

docs_dir: ../docs/global
site_dir: ../site

nav:
  - Home: index.md
  - Platform: /docs/platform/
  - Site Policy: /docs/legal/
