INHERIT: ./_base.yml

site_url: https://mmesh.local/docs/platform/
use_directory_urls: true

docs_dir: ../docs/platform
site_dir: ../site/platform

# nav:
#   - 🡠 Back: /docs/
#   - Getting Started:
#     - getting-started/index.md
#     - Quick start: getting-started/quickstart.md
#     - Features: getting-started/features.md
#     - Integrations: getting-started/integrations.md
#   - Installation:
#     - installation/index.md
#     - Nodes: installation/nodes.md
#     - Command Line Tool: installation/cli.md
#   - Concepts:
#     - concepts/index.md
#     - Architecture: concepts/architecture.md
#   - How-Tos:
#     - Node Linux setup: howtos/node-linux-setup.md
#     - Workflow basics: howtos/workflow-basics.md
#   - Networking:
#     - networking/index.md
#     - Topology: networking/topology.md
#     - Nodes: networking/nodes.md
#     - Network Security: networking/network-security.md
#     - Service Discovery: networking/service-discovery.md
#     - Advanced Features: networking/advanced-features.md
#     - Best Practices: networking/best-practices.md
#   - mmeshctl (CLI):
#     - mmeshctl/index.md
#     - Help: mmeshctl/help.md
#     - Authorization: mmeshctl/authorization.md
#     - Account: mmeshctl/account.md
#     - Alerts: mmeshctl/alerts.md
#     - Tenants: mmeshctl/tenants.md
#     - Networks: mmeshctl/networks.md
#     - Subnets: mmeshctl/subnets.md
#     - Nodes: mmeshctl/nodes.md
#     - Virtual Severs: mmeshctl/vs.md
#     - Policies: mmeshctl/policies.md
#     - Kubernetes: mmeshctl/k8s.md
#     - Automation: mmeshctl/automation.md
#     - Version: mmeshctl/version.md
#     - Completion: mmeshctl/completion.md
#   - Kubernetes:
#     - kubernetes/index.md
#     - Services: kubernetes/services.md
#     - Pods: kubernetes/pods.md
#   - Automation (Ops):
#     - automation/index.md
#     - Projects: automation/projects.md
#     - Workflows: automation/workflows.md
#   - Monitoring:
#     - monitoring/index.md
#     - Analytics: monitoring/analytics.md
#     - Alerts: monitoring/alerts.md
#   - IAM:
#     - iam/index.md
#     - Users: iam/users.md
#     - Authentication: iam/authentication.md
#     - Authorization: iam/authorization.md
#   - Administration:
#     - Tenants: administration/tenants.md
#     - Networks: administration/networks.md
#     - Subnets: administration/subnets.md
#     - Nodes: administration/nodes.md
#     - Kubernetes: administration/kubernetes.md
#     - 'Ops: Projects': administration/ops-projects.md
#     - 'Ops: Workflows': administration/ops-workflows.md
#     - Alerts: administration/alerts.md
#     - 'IAM: Users': administration/iam-users.md
#     - 'IAM: Security Groups': administration/iam-security-groups.md
#     - 'IAM: Roles': administration/iam-roles.md
#     - 'IAM: ACLs': administration/iam-acls.md
#     - User Settings: administration/user.md
#     - Account Administration: administration/account.md
#   - Reference:
#     - 'Node Configuration Reference': reference/mmesh-node.yml.md
#     - 'Command Line Tool Configuration Reference': reference/mmeshctl.yml.md
#     - 'Workflow Configuration Reference': reference/workflow.yml.md
#   - FAQ: faq.md
#   - Tags: tags.md
# 